### ISSUE TITLE
Setup autosplits

### ISSUE THREAD

**Issue by Zutatensuppe** [DiabloRun/DiabloInterface#129]
> Not related but how did you manage to get DI and LiveSplits to work together? I can't get the Game Start auto-split to start the clock when I create a new char

_Originally posted by @agusmagne in https://github.com/DiabloRun/DiabloInterface/issues/42#issuecomment-831180568_

> @agusmagne please check if you have a reset hotkey set up in diablo interface.
> reset hotkey is just triggered directly before start hotkey, so livesplit may think it is an accidental double tap
> to fix this, if you reset by hand anyway, you can unset the reset hotkey in diablo interface
> or if you want to keep it, you can disable double tap prevention in the livesplit settings

> @Zutatensuppe I checked and on my Diablo Interface I don't have any key bound to 'Reset key' and just in case I deactivated the 'Double Tap prevention' in LiveSplits. I'm running both as Admin.
> My LiveSplits splits are configured with 'Game Name' Diablo II: Lord Of Desctruction and I didn't set any Run Category. I added some splits like Andariel and stuff but I don't really know if I'm missing something. I also didn't find any guide on how to turn on the auto-splits on D2 with Diablo Interface and LiveSplits. If you think I'm missing something please let me know. Thanks

**Comment by Zutatensuppe** [comment]
@agusmagne There is only this section in the readme: https://github.com/DiabloRun/DiabloInterface#auto-splits
Can you try these steps and see if it works?
Especially, what happens if you click the 'test hotkey' in diablo interface, does livesplit do anything then?
Or is it really just the game start?

**Comment by agusmagne** [comment]
Oh I didn't read that before. Followed the instructions and now it's working perfectly.
Thanks for developing it and for the support, it's such a great tool. Cheers!
